### ISSUE TITLE
Sub-route and filesystem root

### ISSUE THREAD

**Issue by sveinhansen** [general03/flask-autoindex#15]
Hi

I was wondering if it is possible to use this extension to browser a configurable file-system path at a given sub-route in the application?

```
...
Autoindex(app, <any os path root>

@app.route('/browsefilesystem/<path:path>')
@app.route('/browsefilesystem')
def browse_file_system(path):
    <instruct autoroute to do it's thing>
```

Thanks!

**Comment by eadmaster** [comment]
the answer is [here](https://github.com/sublee/flask-autoindex/issues/9#issuecomment-18869805):
`return idx.render_autoindex(path, endpoint='browse_file_system')`

**Comment by prathameshd9** [comment]
On the view, returning back to parent directory fails dues to an additional "/" at the end.. for example.. returning from /example/example1 --> /example fails as it is looking for a route "/example/". How do we deal with this ?
