### ISSUE TITLE
Index on a path other than root

### ISSUE THREAD

**Issue by blackfist** [general03/flask-autoindex#16]
I'm trying to find documentation on how to configure flask-autoindex to serve up a directory on a route other than /.

   AutoIndex(app, browse_root='some_path')

Works and shows me the content when I visit http://localhost:5000/. I tried to do this

  @app.route('/reports')
  def report_path():
    AutoIndex(app, browse_root='some_path')

And I get an error. What is the proper way to do what I'm trying to do?

**Comment by LarryKlugerDS** [comment]
The following is working for me:

````
files_index = AutoIndex(app, os.path.curdir + '/app/files', add_url_rules=False)
# Custom indexing
@app.route('/files')
@app.route('/files/<path:path>')
def autoindex(path='.'):
    return files_index.render_autoindex(path)

**Comment by general03** [comment]
You're right @LarryKlugerDS it's the solution !
