### ISSUE TITLE
Please do not display milliseconds in last modified field

### ISSUE THREAD

**Issue by meng89** [general03/flask-autoindex#29]
I'm use Linux and python 3.4
The page's last modified fields look like this:

> 2016-04-08 18:55:59.502160

If it is not a feature, I think this will fix it:

flask_autoindex/entry.py:112
`return datetime.fromtimestamp(os.path.getmtime(self.abspath)).replace(microsecond=0)`

Sorry for my bad English

**Comment by general03** [comment]
It will be available on tag v0.6.6

Thanks
