### ISSUE TITLE
render_autoindex sort_by date inverted

### ISSUE THREAD

**Issue by eadmaster** [general03/flask-autoindex#40]
is it possible to change the default sorting when invoking `render_autoindex` without using a custom template?

If i pass the parameters in the url they are lost after the first click:
`http://host/logs?sort_by=modified&order=desc`

I've tried with:
`idx.render_autoindex(path, endpoint = 'logs_view', sort_by='modified', order=-1)`

**Comment by general03** [comment]
In the next release 0.6.4 you can use the order like `return idx.render_autoindex(path, sort_by='-modified')`
