### ISSUE TITLE
python3: ModuleNotFoundError: No module named 'flask.ext'

### ISSUE THREAD

**Issue by johnstile** [general03/flask-autoindex#47]
Fails: from flask.ext.autoindex import AutoIndex
Error: ModuleNotFoundError: No module named 'flask.ext'
site-packages (19.2.1)
pip freeze
Click==7.0
Flask==1.1.1
Flask-AutoIndex==0.6.4
Flask-Silk==0.2
future==0.17.1
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1

**Comment by general03** [comment]
Hello,

Can you put your command and add more explanations

Thanks

**Comment by johnstile** [comment]
It looks like a documentation change is needed for use with newer flask (>=1.0).
REF: https://pythonhosted.org/Flask-AutoIndex/#how-to-use
This code errors:
 from flask.ext.autoindex import AutoIndex
Results in this error:
 ModuleNotFoundError: No module named 'flask.ext'

It looks like this works:
 from flask_autoindex import AutoIndex

**Comment by general03** [comment]
Yes sure, I will update the auto doc

Thanks

**Comment by general03** [comment]
I configured the new online doc, now you will see **soon** it on https://flask-autoindex.readthedocs.io/en/latest/
Indeed the doc push is not more supported on Pypi (https://github.com/WoLpH/sphinx-pypi-upload)
