### ISSUE TITLE
Is it possible to set action for specific file extension?

### ISSUE THREAD

**Issue by bhtsai** [general03/flask-autoindex#50]
First, thank you for this amazing Flask extension.

I have one problem about clicking file with .config extension, it will show this error:
![image](https://user-images.githubusercontent.com/46265189/68065352-0b055800-fd63-11e9-9b4b-0b5cdc4c54c1.png)

I am wondering if it is possible to treat it as txt and then open with browser.

thank you.

**Comment by general03** [comment]
Hello,
Thanks to this congratulation.
I tried to reproduce this issue without success, 

Can you give me your repo link or more explanation to reproduce ?

Thanks

**Comment by general03** [comment]
Without answer I close this issue
