### ISSUE TITLE
Running Autoindex in Docker

### ISSUE THREAD

**Issue by prathameshd9** [general03/flask-autoindex#51]
I am trying to get this up ind Docker.Pretty simple Dockerfile

```
FROM python:3.7.4

WORKDIR /app/
COPY . /app/

RUN pip install -r "requirements.txt"

EXPOSE 5000

ENTRYPOINT ["python", "app.py"]
```
And running as
`docker run --name autoindex -p 5000:5000 -ti javadocs -v /folderview:/app`

Gives me
![Screen Shot 2019-11-22 at 3 57 05 PM](https://user-images.githubusercontent.com/26262448/69466049-fcea9c00-0d50-11ea-8ff7-0c93bc21a39a.png)

I have ppath="/app" in app.py . Any idea on what I might be missing ?

**Comment by general03** [comment]
Hello,

can you put the `app.py` content, and the result of `docker ps` and `curl 1.2.3.4:5000`

Thanks

**Comment by prathameshd9** [comment]
app.py
```
from flask import Flask 
from flask_autoindex import AutoIndex

app = Flask(__name__)

ppath = "/app"

AutoIndex(app, browse_root=ppath)    

if __name__ == "__main__":
    app.run()
```

$docker ps

<img width="989" alt="Screen Shot 2019-11-25 at 9 52 32 AM" src="https://user-images.githubusercontent.com/26262448/69550768-95f3ff80-0f69-11ea-9eeb-c9d4efac0da5.png">


<img width="767" alt="Screen Shot 2019-11-25 at 9 50 23 AM" src="https://user-images.githubusercontent.com/26262448/69550531-2716a680-0f69-11ea-9582-60bce248509f.png">

**Comment by general03** [comment]
Hello,

Sorry for the delay, It's configuration docker issue as you can see
`docker exec -it javadocs curl 127.0.0.1:5000`
With this command you can see the content page of Flask Autoindex

**Comment by general03** [comment]
- You can specify the network `host`with docker like `docker run --network host --name autoindex -p 5000:5000 -ti javadocs -v /folderview:/app` (development case)
- You have to use reverse proxy to serve your application (production mode)
