### ISSUE TITLE
Flask-login for every paths

### ISSUE THREAD

**Issue by francoisihry** [general03/flask-autoindex#52]
Hi,

I need to protect the access to my flask server with flask-login.

This is done by adding @login_required to the path I need to protect.
Example:
```
@app.route("/my/path")
@login_required
def test():
    return 'hello'
```

With flask-autoindex the paths are dynamic, how can I force the user to login for every path ?

**Comment by general03** [comment]
Hello,

Why do not want to use `@login_required` decorator ?

**Comment by general03** [comment]
Without answer I close this issue
