### ISSUE TITLE
Flask-Autoindex 0.6.4 does not work with Werkzeug 1.0.0

### ISSUE THREAD

**Issue by OryJonay** [general03/flask-autoindex#53]
Importing "cached_property" from werkzeug does not work anymore (https://github.com/general03/flask-autoindex/blob/master/flask_autoindex/__init__.py#L10), it should be imported from werkzeug.utils (https://github.com/pallets/werkzeug/blob/master/src/werkzeug/utils.py#L53).

There are probably more imports that need to be fixed, or just pin version of Werkzeug to 0.16.0.

**Comment by general03** [comment]
Hello, I merged the fix https://github.com/general03/flask-autoindex/pull/54 now
