### ISSUE TITLE
Please fix licensing ambiguation

### ISSUE THREAD

**Issue by highvoltage** [general03/flask-autoindex#55]
Hi, it seems that the license of flask-autoindex has changed from a BSD 3 clause to an MIT license.

However, there's no COPYING or COPYRIGHT file that specifies which MIT license (I assume the MIT Expat license since that is commonly used). Also, the documentation in docs/index.rst still declares that the project is released under the BSD license. Please clarify.

As a side-note, it seems that you've released version 0.6.5 on pypi, but haven't tagged the release yet in your git repository.

Thanks for your work.

**Comment by general03** [comment]
Hello,

> However, there's no COPYING or COPYRIGHT file that specifies which MIT license (I assume the MIT Expat license since that is commonly used). Also, the documentation in docs/index.rst still declares that the project is released under the BSD license. Please clarify.

You can see the right licence is under MIT : https://github.com/general03/flask-autoindex/blob/master/docs/index.rst#licensing-and-author

> As a side-note, it seems that you've released version 0.6.5 on pypi, but haven't tagged the release yet in your git repository.

It's done ;-)
