### ISSUE TITLE
Autoindex send file images as attachment

### ISSUE THREAD

**Issue by Anamura** [general03/flask-autoindex#62]
Hello!

could you please clarify, is it possible to download images from autoindex as attachment
not via opened in browser.

thank you

**Comment by 4n1qz5skwv** [comment]
Hi, I already opened an issue about it. But not only for image but also video, pdf... (all files). 

https://github.com/general03/flask-autoindex/issues/60

**Comment by Anamura** [comment]
thank you for info, will close this as duplicate
