### ISSUE TITLE
Basic example fails with werkzeug.routing.BuildError

### ISSUE THREAD

**Issue by permind** [general03/flask-autoindex#9]
Hi, 
autoindex works when it is enabled by default on all routes (add_url_rules=True).
If I try autoindex on a specific route, it fails with werkzeug.routing.BuildError.
What I am doing wrong?
Code:

from flask import Flask
from flask.ext.autoindex import AutoIndex
app = Flask(**name**)
idx = AutoIndex(app,'/', add_url_rules=False)

@app.route('/')
def app_root():
    return 'Hi!'

@app.route('/index')
def index():
    return idx.render_autoindex('.')

if **name** == '**main**':
    app.run(host='0.0.0.0', debug=True)

**Comment by MignoneDev** [comment]
kiendly help am getting the following error werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'login' instead?

from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from app import app, db 
from app.forms import LoginForm, RegistrationForm
from app.models import User, Post
from werkzeug.urls import url_parse
from datetime import datetime



@app.route('/')
@app.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = [
        {'author': user, 'body': 'Test post #1'},
        {'author': user, 'body': 'Test post #2'}
    ]
    return render_template('user.html', user=user, posts=posts)


@app.route('/')
@app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        flash('Login requested for user {}, remember_me={}'.format(
            form.username.data, form.remember_me.data))
        return redirect(url_for('index'))
    return render_template('login.html', title='Sign In', form=form)

    # adds the database instance and models to the shell session:


    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('index')
        return redirect(next_page)

    # adds the database instance and models to the shell session:

@app.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('login'))
    return render_template('register.html', title='Register', form=form)


@app.shell_context_processor
def make_shell_context():
    return {'db': db, 'User': User, 'Post': Post}

@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))


@app.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
